### ISSUE TITLE
Potential `srcset` parsing error

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/picture-element#166]
We’re writing Picturefill tests for some of @yoavweiss’ more horrifying native tests, and we came across this little gem: `1x,,  ,   x    ,2x  , 1x.gif, 3x, 4x.gif 4x 100h, 5x.gif 5, dx.gif dx, 2x.gif   2x ,`

While trying to make sense of it talking to @tabatkins, he realized that the current algo means that `foo,bar 2x`—which should be functionally equivalent to `foo, bar 2x`, `foo 1x,bar 2x`, or `foo 1x, bar 2x`—gets processed as a URL of `foo,bar` to be displayed in 2x environments. @tabatkins was saying something about needing to enforce the space in the spec?

**Comment by yoavweiss** [comment]
I'm not sure how we can address this without breaking URLs with commas in
them.

**Comment by tabatkins** [comment]
So, one thing that should be fixed in the algo is that it inconsistently skips over either the comma ending a source _or_ the first whitespace _after_ the comma, depending on if there's any descriptors.  This _happens_ to work, but the difference has no reason to be there, and it's a landmine for future changes to the algorithm.

Specifically, say you have "foo 1x, bar".  This parses into a url of "foo" with descriptors of " 1x", and a leftover of ", bar".  We move the position forward one (getting " bar"), then parse out a url of "bar".

But if we don't have any descriptors, like "foo, bar", then we parse out a url of "foo,", drop the trailing comma (getting "foo"), and have a leftover of " bar".  We move the position forward one (getting "bar" - note the lack of initial space), then parse out a url "bar".

So we do happen to get compatible results, but in one case when we move the position forward we jump over the comma separating the sources, while in the other we jump over the first whitespace _after_ the comma separating the sources.  We should tweak to either always start parsing the next source from the stuff immediately after the comma, or immediately after the first whitespace.

**Comment by tabatkins** [comment]
Further stuff - the current algo makes it impossible to, for example, ever add a function with comma-separated arguments to the grammar.  It'll stop at the first comma in the arglist and then start parsing a new source out of the rest.  This is future-hostile.

I'd like to rewrite this to use CSS parsing, like sizes='' does, but we can't, because URLs are crazytown.  We can't even say "collect component values until we hit whitespace, then concat all their representations", because urls like "http://example.com/#foo(bar" are valid.  I'll have to do some tweaks while maintaining roughly the current algo structure, I think.

**Comment by tabatkins** [comment]
Ooh, another bit of weirdness:

The current algo allows you to have a url that ends with a comma _if you don't have any descriptors_: "foo,, bar" gives you the urls "foo," and "bar".  But that's impossible to get if you have any descriptors: "foo, 1x, bar" gives three urls - "foo", "1x", and "bar".

**Comment by zcorpan** [comment]
To support functions with commas, how about collecting characters until you hit a space character to gather the URL, and then collect component values until you hit a comma-token to gather the descriptors?

**Comment by zcorpan** [comment]
About trailing comma in the URL, I don't disagree that it seems a bit weird, but what can we do about it? I don't see a sane way to change the parsing to somehow make it consistent. As for authoring conformance, "foo,, bar" is already invalid because the URL ends with a comma. http://picture.responsiveimages.org/#image-candidate-string

**Comment by zcorpan** [comment]
Maybe we could stip off all trailing commas instead of just the last one?

**Comment by tabatkins** [comment]
We can't use the "consume a component value" algo unless we're using CSS tokenizing, which we can't do because URLs are extra-magic (we can't even do some special-cased CSS tokenizer, because a URL looks like _everything_, so you can't do independent tokenization).  We'll have to hand-roll ()[]{} tracking, which isn't hard, but is annoying.

And yes, I think we should strip off all trailing commas.

**Comment by zcorpan** [comment]
Do we need really [] {} or is it enough with ()?

**Comment by tabatkins** [comment]
Might as well be fully forward-compatible-equivalent with CSS.  Tracking all three is only a tiny bit more complicated than tracking just one; you have to use a character stack rather than a nesting counter.

**Comment by yoavweiss** [comment]
Where do we stand on this issue?

**Comment by zcorpan** [comment]
Can't we go with the simplest thing to support commas in functions? Just have a boolean flag that gets set when seeing `(` and unset when seeing `)`, then ignore `,` while the flag is set. Or do you envision nesting functions @tabatkins ?

**Comment by yoavweiss** [comment]
:+1: to keeping it simple
