### ISSUE TITLE
Ban functions in sizes other than calc()

### ISSUE THREAD

**Issue by zcorpan** [ResponsiveImagesCG/picture-element#241]
It's not super clear what toggle() and attr() should do in sizes="". We should just ban anything but calc().

**Comment by tabatkins** [comment]
`toggle()` technically works, but since there's no inherited value, it'll just always select its first value. Fine to ban it.

`attr()` is technically only defined within the context of a property, which `sizes` isn't, so it doesn't actually work. Fine to ban it too.

I agree that it should be fine to just whitelist `calc()`, and we can expand the list in the future if needed.
