### ISSUE TITLE
Simpler to implement source selection?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#39]
Following the latest feedback from the Blink team RE [increased PreloadScanner complexity](https://groups.google.com/a/chromium.org/forum/?fromgroups=#!topic/blink-dev/MlE9vYVUlzg) in our current source selection algorithm, do we want to modify it so that _all_ matching sources are downloaded (even if only the first one is displayed)?
That will force webdevs to specify non-overlapping MQs for sources:

```
<picture>
    <source src="big.jpg" media="screen and (min-width: 800px)">
    <source src="small.jpg" media="screen and (max-width: 799px)">
</picture>
```

This is already the case for non-matching external CSS files, so it might be a good practice to teach devs to do that. However, if devs don't markup their `media` attributes that way, it can result in a significant negative performance impact.

Thoughts?

**Comment by marcoscaceres** [comment]
Argh... :frowning:. This seems like a pretty significant compromise. Need to chew on this for a bit.

**Comment by Wilto** [comment]
I’m opposed to this change, I won’t lie. It would make the process a lot more painless for us, for certain, but we’d only end up with something I would end up ignoring and replacing with a custom script.

**Comment by marcoscaceres** [comment]
I'm thinking the same thing... I automatically thought of `<img lazy>` as a work around.

**Comment by anselmh** [comment]
Agree with Marcos and Mat here. Of course we should teach devs to write proper media-queries but it does not make too much sense to go this compromise as this can have this huge performance impact. And as we all know, we created the solution for better (not worse) performance.

**Comment by yoavweiss** [comment]
So we have consensus against this. Closing.

**Comment by marcoscaceres** [comment]
Ok, we all agree it sucks. But what do we do now? I'd like us to only close this once we have a clear course of action.

**Comment by yoavweiss** [comment]
OK. The basic concept that adds to the impl complexity here is the "bundle". The resources cannot be handled independently forcing the implementation to keep state (and pass that state between threads). 
Anyone has an idea how it can be solved without burdening devs?

**Comment by anselmh** [comment]
@yoavweiss I am not sure if I understand that correctly. Can you explain a bit more in detail what is the problem we're facing here?

**Comment by yoavweiss** [comment]
The feedback I got from the Blink people is that `<picture>` adds complexity to the PreloadScanner.
Part of that complexity is the fact that the MQs need to be evaluated before the resource is loaded, which is inherent to  `<picture>`, but shared by other resources loaded by their media attributes (currently only external CSS).
The different part about picture is that its child nodes' resources must be treated in coordination. The current algorithm states that the first matching one must be picked. That forces the preloader to keep state, and pass that state (in one way or another) to a different thread that is in charge of the actual loading.
If we could modify the resource selection algorithm so that each `<source>` element can be treated separately, but still keep it simple for WebDevs, that'd be a win-win and will increase the chances of getting browser buy-in.

I'm not sure how this can be done. It is possible that we must compromise implementation simplicity for developer comfort here. If anyone has any brilliant ideas, I'd love to hear them.

**Comment by nwtn** [comment]
What happens with `<video>` and the PreloadScanner?

**Comment by yoavweiss** [comment]
Nothing. Videos sources are not being preloaded (even if they have the
`preload` attribute)

**Comment by nwtn** [comment]
Just spitballing here, and haven't really thought through in detail; please feel free to point out glaring stupidities. If _all_ MQs are defined early (say in `head`), could a separate scanner evaluate those and choose the winning one? something like this:

```
<head>
  <mediaquery id="mq1" media="screen and (min-width: 800px)" />
  <mediaquery id="mq2" media="screen and (min-width: 320px)" />
  <mediaquery id="mq3" media="screen" />
</head>
<body>
  <picture>
    <source src="big.jpg" media="#mq1">
    <source src="med.jpg" media="#mq2">
    <source src="small.jpg" media="#mq3">
  </picture>
</body>
```

Let's say this is loaded in a viewport 1000px wide. In this example the MQ scanner would encounter the MQs in the head and decide that although all three matched, it only cares about the first one, `#mq1`. (This decision would still require coordination and keeping state, but maybe this isn't an issue if it's outside the PreloadScanner and just happens once.)

The winning MQ would be available to the PreloadScanner and the PreloadScanner would match against this, rather than evaluating each MQ it encounters. So when the PreloadScanner hits the `<source>` elements, it matches on `#mq1` and loads `big.jpg`, without loading the other two resources.

The difference in the selection algorithm from what we had before is that it isn't loading the first `<source>` that matches, but loading _any_ `<source>` that matches the _first matching MQ_. With this, devs would be defining their MQs once and worrying about order then, but order of `<source>` elements would be basically irrelevant. This:

```
  <picture>
    <source src="small.jpg" media="#mq3">
    <source src="med.jpg" media="#mq2">
    <source src="big.jpg" media="#mq1">
  </picture>
```

...would still load `big.jpg`.

I'm sure there's something really basic I'm overlooking here (especially since I know defining MQs in the head has come up before, and been dismissed), but maybe this can spark some useful discussion.

Also...even if this is actually a good idea, it falls apart when combining `media` and `type` attributes I think.

Anyway, thoughts?

**Comment by nwtn** [comment]
[prev discussion of setting MQs in head](http://www.w3.org/community/respimg/2012/05/13/an-alternative-proposition-to-and-srcset-with-wider-scope/)

**Comment by aarongustafson** [comment]
Yeah, Matt’s discussion is really helpful, thanks for linking that up @nwtn!

One thing I want to point out in terms of the logic in your concept here is that in your example of a 1000px wide screen, all three of your proposed queries do match. It is only when you use them in `picture` that the first-match rule would come into effect.

To clarify why that should be: think about loading 3 CSS files with those exact media queries. All three would apply. The existence of `picture` (or `video`) creates the "choose one" scenario.

**Comment by nwtn** [comment]
That's true, the first match bit would only apply to `picture` (and possibly `video` etc). That means we'll need to send the "winning" match to PreloadScanner, but other things (e.g. CSS) might need all matches, not just the first one. Given that, this MQ scanner could save all matches, but only pass something like `matches[0]` into the PreloadScanner.

**Comment by yoavweiss** [comment]
In general I favor the approach of defining MQ "shortcuts" in the document's head (I'm not sure which of the proposed syntax is better), but it should probably pass through www-style, since this is bigger than responsive images alone (It can be useful for style loading, inside style definitions, `<video>`, etc).

I'm also not sure we can _mandate_ the use of these "shortcuts" in order for `<picture>` to work. If we can't, it won't simplify implementation (even though it may simplify use by Web devs)

As far as WebKit/Blink implementation goes, if we could mandate that, we could probably pass the PreloadScanner the matching queries, and there'd be no need to re-evaluate them (saving the need to pass through the main thread). The "first match" algorithm is not an issue, once we saved the need to pass state to the main thread.

I'm not sure it'd simplify things for Gecko/Trident/others, even though it makes sense that it would.

I guess the 2 questions we need to answer in that respect:
- Should we wait for MQ shortcuts to happen? Is it a subject we can promote in www-style?
- Can we _mandate_ the use of MQ shortcuts for `<picture>`?

**Comment by aarongustafson** [comment]
> Should we wait for MQ shortcuts to happen? Is it a subject we can promote in www-style?

There’s no harm in running it up the flagpole.

> Can we _mandate_ the use of MQ shortcuts for `<picture>`?

I’m not against the pre-definition of MQs in the head (though I’m holding off on talking syntax for now). I am, however, against _requiring_ them for `picture` as it seems an author may want to make an exception on a per-`picture` basis. If they do so with the understanding that the page is not going to perform as well (because it messes with the PreloadParser), that’s fine, but let’s say (for argument’s sake) a specific photo would look best cropped a particular way in a breakpoint other than the major ones covered at the document level. Shouldn’t an author be able to create a one-off `source` or a full-blown `picture` that does not reference the document-level MQs?

**Comment by nwtn** [comment]
> I’m not against the pre-definition of MQs in the head (though I’m holding off on talking syntax for now). I am, however, against requiring them for picture as it seems an author may want to make an exception on a per-picture basis.

+1.

I don't think we have to mandate this for `picture`, we only have to mandate it for `picture` _with preloading_. If an author wants to have a one-off exception, I don't think it's an unreasonable tradeoff to have that exception handled outside of the PreloadScanner.

**Comment by yoavweiss** [comment]
I guess that's for the implementors to decide (since preloading is not specified anyway), but it can work as a compromise, similar to what happened with external CSS for a long while.

**Comment by nwtn** [comment]
Anyone interested in posting this to www-style? I'm not on that list, but am happy to join/post if nobody else is up for it.

**Comment by yoavweiss** [comment]
I suggest starting out an etherpad and sketch out something.
I don't think we should make any proposals at this point, but simply raise
this use-case and see what the guys over there say.
Can you do that? (I'm kinda swamped ATM...)

**Comment by anselmh** [comment]
Well, I don't have the time to write something but am on the list. If you come up with a proposal of text we can review then I can send this out (or someone else here, think there are enough on this list here).

**Comment by nwtn** [comment]
Good call on EtherPad: http://openetherpad.org/eBbC3DY0jq. If anybody's feeling creative, feel free to start working on it.

**Comment by yoavweiss** [comment]
Wrote to www-style:http://lists.w3.org/Archives/Public/www-style/2013May/0638.html a while back.
All in all they seems favorable to the idea, but the exact method still needs to be worked out.
No timelines as to when this work will actually happen.

**Comment by marcoscaceres** [comment]
Can we close?

**Comment by Wilto** [comment]
Sure; closin’.
