### ISSUE TITLE
What's the need for the source-set list?

### ISSUE THREAD

**Issue by yoavweiss** [ResponsiveImagesCG/picture-element#80]
Going over the algorithms, I noticed that the [selection algorithm](http://picture.responsiveimages.org/#select-image-source) picks consistently the first element from the the source-set list and ignores other source-sets in it entirely.
As far as I can tell, no one else is using that list.

If my understanding is correct, it would be more efficient to simply return the first source set parsed in the [update source sets algorithm](http://picture.responsiveimages.org/#update-source-sets), and avoid creating the list at all.

Thoughts?

**Comment by yoavweiss** [comment]
@tabatkins - ping

**Comment by tabatkins** [comment]
I believe my thoughts where that if we allow annotating individual sources with a type (rather than requiring them to be put in a separate <source>), then it's possible for a source set to be selected, but none of the sources match.

That's not possible yet, though, and in any case, we can just drop those sources as we go along, and then just not add empy source sets to the list, so that problem case disappears.

So yeah, I think you're right that we can just eliminate it from the algo.
